languageCode = "es-ES"
title = "Cristian F. Patiño Rojas"
publishDir = "public"

[permalinks]
	escritura = "/:filename"
	trad = "/:filename"
	otros = "/:filename"
	transc = "/:filename"

# Allows rendering the html inside markdown
[markup.goldmark.renderer]
unsafe= true

[markup]
[markup.highlight]
	codeFences = false


[module]
[[module.imports]]
path = "github.com/crisrojas/cristianlat-content"
disabled = false

[[module.imports.mounts]]
source = "content"
target = "content"

