languageCode = "es-ES"
title = "crisrojas"
publishDir = "public"
pygmentsUseClasses=true
googleAnalytics = "UA-123910995-2"

[params]
    # Specify favicon (icons/i.png maps to static/icons/i.png). No favicon if not defined.
    favicon = "favicon.ico"
    author = "Cristian Rojas"

# Allows rendering the html inside markdown
[markup.goldmark.renderer]
unsafe= true

