languageCode = "es-ES"
title = "Cristian F. Patiño Rojas"
publishDir = "public"

[permalinks]
	escritura = "/:filename"
	trad = "/:filename"
	otros = "/:filename"

# Allows rendering the html inside markdown
[markup.goldmark.renderer]
unsafe= true