languageCode = "es-ES"
title = "Cristian F. Patiño Rojas"
publishDir = "public"

[permalinks]
	escritura = "/:title"
	trad = "/:title"

# Allows rendering the html inside markdown
[markup.goldmark.renderer]
unsafe= true